name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install -d

      - name: Run isort
        run: |
          pipenv run isort .

      - name: Run black
        run: |
          pipenv run black .

      - name: Run flake8
        run: |
          pipenv run flake8 .

  test:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install -d

      - name: Run tests
        run: |
          pipenv run pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Setup up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pipenv install -d

      - name: Run CDK diff
        run: |
          ENV=ci pipenv run cdk diff --app stack/app.py
